### PR TITLE
Enable Applicative optimization

### PR DESCRIPTION
**Pull request by ElvishJerricco**
`eff-transformer` currently has an issue with its Applicative instance. `(<*>) = ap`! For monads like [Haxl](https://github.com/facebook/Haxl), this is a huge problem. Sometimes, you need to handle applicative effects differently than monadic ones.

To this end, I've come up with an encoding of the Freer monad that retains applicative effects. Originally, Freer was just the composition of Lan and Free. [The Free Applicative](http://hackage.haskell.org/package/free-4.12.4/docs/Control-Applicative-Free.html), can be used in Lan's place, as `liftA` defines a suitable Functor instance for it. This composition ends up looking like this.

``` Haskell
data Freed f a
  = Val a
  | forall b. (Freed f (b -> a)) :<*> (f b)
  | forall b. (f b) :>>= (b -> Freed f a)

instance Functor (Freed f) where
  fmap f (Val a) = Val (f a)
  fmap f (g :<*> x) = fmap (f .) g :<*> x
  fmap f (x :>>= k) = x :>>= (fmap f . k)

instance Applicative (Freed f) where
  pure = Val
  Val f <*> a = fmap f a
  (f :<*> x) <*> a = (flip <$> f <*> a) :<*> x
  (x :>>= k) <*> a = x :>>= ((<*> a) . k)

instance Monad (Freed f) where
  Val a >>= k = k a
  (f :<*> x) >>= k = x :>>= \b -> fmap ($ b) f >>= k
  (x :>>= k') >>= k = x :>>= (k' >=> k)
```

Given the proofs that `Ap` obeys the Applicative laws, and `Free` obeys the monad laws, it is proven that the above `Freed` obeys these laws as well.

For any free monad, you can construct a monad transformer by applying `Sum f m` to it. Doing this on `Freed` leads to this definition of `Eff`.

``` Haskell
data Eff f m a
  = Val a
  | forall b. (Eff f m (b -> a)) :<*> (Sum f m b)
  | forall b. (Sum f m b) :>>= (b -> Eff f m a)

instance Functor (Eff f m) where
  fmap f (Val a) = Val (f a)
  fmap f (g :<*> x) = fmap (f .) g :<*> x
  fmap f (x :>>= k) = x :>>= (fmap f . k)

instance Applicative (Eff f m) where
  pure = Val
  Val f <*> a = fmap f a
  (f :<*> x) <*> a = (flip <$> f <*> a) :<*> x
  (x :>>= k) <*> a = x :>>= ((<*> a) . k)

instance Monad (Eff f m) where
  Val a >>= k = k a
  (f :<*> x) >>= k = x :>>= \b -> fmap ($ b) f >>= k
  (x :>>= k') >>= k = x :>>= (k' >=> k)

instance MonadTrans (Eff f) where
  lift = (return id :<*>) . InR
```

Running the benchmarks, I get roughly 2.5x slow-downs from `eff-transformer`'s current implementation. This isn't too bad, but it's counter to the goal of being as fast as `mtl`. At least part of the issue is that `fmap` is `O(n)`, so `(<*>)` is `O(n^2 + m)`. This encoding is just inherently slow.

In 2013, [Dave Menendez](https://www.eyrie.org/~zednenem/2013/05/27/freeapp) discovered this same performance problem on the free Applicative. In that article, he described a method of greatly improving the performance, reducing every operation to `O(1)`, except for the interpreter, which was `O(n)`. [He went on](https://www.eyrie.org/~zednenem/2013/06/freeapp-2) to discuss more encodings based on church encoding.

I'm opening this pull request largely to discuss the merits of this approach, and how we might improve its performance. I'm not entirely sure how to bring Dave's work into this encoding, but I think those articles are a good start.

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
I should add, I tried implementing with [Reflection Without Remorse](http://okmij.org/ftp/Haskell/zseq.pdf), via the `type-aligned` package, but found that the overhead actually made performance worse in the benchmarks. I'm sure there's plenty of cases where that overhead would be worth it, but I don't think it's the right choice for this.

**Comment by ElvishJerricco** [comment]
I had apparently incorrectly implemented the application of the free applicative to the free monad (I accidentally applied it to the Freer monad and made a law-breaking optimization). Thus, the monad laws were broken in that implementation.

I've just pushed a commit with the free applicative properly applied to the free monad. It's a naive implementation, so the performance is far from optimized, and is currently performing about 5x slower than mtl. But again, the goal of this pull request is to determine how to optimize it to mtl speeds.

For what it's worth, I made a local test and found that the applicative effects were in fact working as desired. It is possible to get the applicative benefits of Haxl with this implementation.

**Comment by ocharles** [comment]
Part of the performance magic from my implementation comes from aggressively `INLINE`ing everything. I see you've defined `Functor` and friends for `Eff`, but haven't added an `INLINE` pragma. Give that a try and see how performance looks.

**Comment by ElvishJerricco** [comment]
Ah yea forgot to do the inlining.

Shows a small improvement, but nothing to write home about. Just a little less than 5x slower than mtl.

**Comment by ElvishJerricco** [comment]
The performance problems come from the extremely recursive nature of this implementation. `fmap` is _O(n)_, and other operations are even worse.

**Comment by ocharles** [comment]
Yea, indeed - but sometimes when you get a lot of inlining GHC works some serious magic. It's a cheap hammer that can be worth trying.

**Comment by ElvishJerricco** [comment]
Yea. Adding inlining helped a little, but it's still got a long way to go.

**Comment by ElvishJerricco** [comment]
I'm going to close this. Ultimately, I think I would have to figure out a way to church encode [my applicative optimized free monad](http://elvishjerricco.github.io/2016/04/08/applicative-effects-in-free-monads.html), which I've not yet figured out. Maybe I'll reopen / restart if I ever figure that out.

**Pull request closed without merging**
